version: '3.4'

services:
  music_radio:
    image: sanmmmm/music_radio:${MUSIC_RADIO_TAG:-latest}
    ports:
      - 3001:3001
    volumes: 
      - server-log:/data
      - ${CONFIG_DIR:-server-config}:/app/backend/build/backend/config
    restart: always
    depends_on: 
      - redis
      - neteaseapi
  redis:
    image: redis
    volumes:
          - redis-data:/data
    restart: always   
  neteaseapi:
    image: binaryify/netease_cloud_music_api
    environment: 
      - no_proxy=*
    restart: always 
volumes: 
  redis-data:
  server-log:
  server-config: