name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      neteaseapi:
        image: binaryify/netease_cloud_music_api
        ports:
          - 3000:3000
    strategy:
      matrix:
        node-version: [12.x, 14.x]
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: run test
      run: npm test
      env: 
        REDIS_URL: redis://localhost:6379
        NETEASE_API_URL: http://localhost:3000  
